[project]
name = "pyprj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.5",
    "pandas>=2.3.1",
    "scipy>=1.16.1",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]
